### ISSUE TITLE
Update context language for wave procedure

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/wavelab#1]
Language is the same for both options, at a glance it appears the 'wave' option is incorrect. 
![image](https://user-images.githubusercontent.com/12058013/53358857-6db67200-38ff-11e9-8381-10ebc66d64eb.png)
![image](https://user-images.githubusercontent.com/12058013/53358875-77d87080-38ff-11e9-802e-4f63cf61912f.png)

**Comment by jknewson** [comment]
This comes from the services
closed and moved to https://github.com/USGS-WiM/WaveLabServices/issues/1
